#ifndef SOUNDPLAYERLIB_GLOBAL_H
#define SOUNDPLAYERLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SOUNDPLAYERLIB_LIBRARY)
#  define SOUNDPLAYERLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SOUNDPLAYERLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SOUNDPLAYERLIB_GLOBAL_H
